== Composites

Generate values of basic types is great but sometimes we may want to
create instances of more complex types such as maps, lists, or pojos.

=== Tuple

A tuple is a finite ordered list of elements. As we'll see afterwards
you can create random sized lists with the `list` generator, but if
you only wanted to create a fixed sized lists with fixed types,
`tuple` could be your best option.

[source,groovy]
.Tuple
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=tuple,indent=0]
----

In this example we're creating a tuple (a fixed list) of three elments
of types: Integer, Integer and String.

=== List

As we've just seen you can create fixed lists with `tuple` but if you
want to vary the size of the list, or use random element types then
you should be using `list`. A list needs a given value generator to
take its elements from and could have some size constraints like the
minimum or/and maximum number of elements. A basic list generator
without any size boundaries:

[source,groovy]
.Simple list
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=simplelist,indent=0]
----

<1> `list(valueGenerator)` in this case we are using the `integer`
generator to create values of type `Integer`

This example generates random sized lists with values taken from the
value generator passed as parameter.

**List length**

On the other hand if you want to establish some size boundaries you
could use `list(valueGenerator,min,max)` or
`list(valueGenerator,max)`.

[source,groovy]
.List with size boundaries
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=sizedlist,indent=0]
----

<1> Creating a list with a minimum size of 1 and a maximum of 5
<2> It should be an instance of list
<3> It should have a minimum size of 1
<4> It should have a maximum size of 5
<5> All elements should be of type integer

=== Map

You can create instances of `java.util.Map` and also specify which
type of values should be used per `key-value` entry.

[source,groovy]
.Map
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=mapgenerator,indent=0]
----

<1> Declaring a `map` generator
<2> Declaring `id` will be a long
<3> Declaring `name` will be a string
<4> Declaring `age` will be an integer between 0 and 120. Then we get
`next()` map generated value

=== Type

Given a class we may want to create a generator that can supply
instances of that type. Here is an example of a given class:

[source,groovy]
.Data
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=data,indent=0]
----

The following generator creates instances of the previous type and it
has defined a different generator for each field:

[source,groovy]
.Generator
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=typegenerator,indent=0]
----

<1> Create generator
<2> Take next instance

In the following example the type we would like to get instances from
has a non default constructor:

[source,groovy]
.TupleData
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=tupledata,indent=0]
----

But that is not an issue, as long as we respect the number of
arguments after declaring the class.

[source,groovy]
.Generator
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=typegenerator2,indent=0]
----

NOTE: Notice here we are generating the same name for the `i` field
over and over again (42)


=== Combinations with `permute`
Under some conditions you may want to test all combinations of inputs. Tuple, map with fixed keys, and type generators all
implement the
https://github.com/Bijnagte/spock-genesis/blob/master/src/main/groovy/spock/genesis/generators/Permutable.groovy[Permutable]
interface to accomplish that in a lazy fashion.

IMPORTANT: Iterating through all combinations expands the number of iterations exponentially.

Outputs are produced using a depth first algorithm. Setting the max depth limits the number of values that are produced for
each input.

[source,groovy]
.using a map generated POJO
----
include::{testDir}/spock/genesis/generators/composites/PojoGeneratorSpec.groovy[tags=mapgenerator,indent=0]
----

<1> Declaring a generator
<2> Call `permute` and get all of the values
<3> The result contains all of the combinations
<4> Call `permute` setting a max depth of 2 and get all the values
<5> The result only contains the combinations of the first 2 values from each field

If no max depth is specified then the formula stem:[ |__root(n)(10000)__| ] is used to determine the max depth

.number of iterations
|===
| input count | depth | iterations
| 1           | 10000 | 10000
| 2           | 100   | 10000
| 3           | 21    | 9261
| 4           | 10    | 10000
| 5           | 6     | 7776
| 6           | 4     | 4096
| 7           | 3     | 2187
| 8           | 3     | 6561
|===

Groovy provides a http://docs.groovy-lang.org/latest/html/api/groovy/util/GroovyCollections.html#combinations(java.lang.Iterable)[combinations] method that provides a similar capability but it is not lazy and does not control for the
exponential issue.