== Output
Some times you need to control the output of a generator.

=== Seeding random generation

For random generators it can be useful to control the seed for random generation.
This will cause a consistent sequence of values to be generated by an equivalent generator.

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=seed,indent=0]
----

Setting the seed to different values will vary the output but will always produce the same sequence.
[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=differentseed,indent=0]
----

=== Using `with`

You can use `with` if you would like to set some property of the
generated value.

IMPORTANT: `with` is different from the default groovy implementation! It always returns a new generator.

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=datewith,indent=0]
----

=== Transforming with `map`

Sometimes output needs to be converted to another type. the `map` method works
like groovy's `collect` but will return a new generator that lazily performs the
transformation. An example would be calling the `toString()` method.

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=transform,indent=0]
----