== Values

Values could be of any simple type such as a String, Integer,
Byte...etc Before using any built-in generator remember to add the
following import:

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=genimport,indent=0]
----

Then you should be able to generate a simple value from the available
generators:

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=factorymethods,indent=0]
----

These examples are creating only the next available generated value
from the corresponding generator. This way of using simple types
generators doesn't put any constraint to the generated value apart
from generate a specific type of value. We'll see later on how to add
some boundaries to some of the value generators. For the time being,
if for example, we would like a string we won't care about the length
of the string.

=== Strings

Like we saw in the previous section if we don't care about the length
or the content and we just wanted to generate a string then it's
enough to call `Gen.getString()` or in a more `groovier` way
`Gen.string`

**By length**

In case we wanted to restrict the generated word length, we could use
one of the following methods:

[source,groovy]
.Restricting string length
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=stringlength,indent=0]
----

<1> Establishing the maximum string length
<2> Establishing both minimum and maximum length

**By pattern**

[source,groovy]
.From a string pattern
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=stringregex,indent=0]
----

=== Numbers

`spock.genesis.Gen` has access to several number generators. All basic
number types have a direct method to generate a random value without
establishing any restriction.

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=numbers,indent=0]
----

For integers there are a couple more methods to set the boundaries of
the generated values directly.

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=integerlength,indent=0]
----

<1> Using a Groovy range to establish min and max boundaries
<2> Establishing min and max using two parameters

=== Date

In many applications could be handy to generate dates to validate some
principles. For instance when booking a room to make sure the system
doesn't accept any check-out done the same date or before as the
check-in right ?

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=dates,indent=0]
----

=== From value

You've seen several ways of creating values from simple data
types. But if you still wanted to create an infinite lazy generator
for a given value you can use `Gen.value`

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=value,indent=0]
----

=== From enum

If you already have an enum type and you would like to generate random values
from it, then you could use `these`:

[source,groovy]
----
include::{testDir}/spock/genesis/SamplesSpec.groovy[tags=fromenum,indent=0]
----

NOTE: `these` in general can generate values taken from a given
source, in this case the source is an enum. To know more about `these`
check the section `combine`.
